name: Async Impulse
title: Async Impulse | Alastor Wu
description: Alastor Wu's personal website
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
email: alastor0325@gmail.com
disqus_username: alwu
